// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

package main

import "fmt"

func fib(in [2]int) [2]int {
	return [2]int{in[1], in[0] + in[1]}
}

func main() {
	n := [2]int{1, 2}
	sum := 0

	for n[1] < 4000000 {
		if n[1]%2 == 0 {
			sum += n[1]
		}

		n = fib(n)
	}

	fmt.Println(sum)
}
